#!/bin/sh

PATH=`pwd`/bin:$PATH
if [ -f demo_env.sh ]; then
    . ./demo_env.sh
fi

export VAULT_TOKEN=${VAULT_ROOT_TOKEN}
export MYSQL_HOST=${DB_HOSTNAME}
export MYSQL_TCP_PORT=${DB_PORT}

clear
echo "Let's now generate some tokens with the sakila-admin policy"
echo
echo
echo "vault token create -policy sakila-admin"
vault token create -policy sakila-admin -format=json > sakila-admin.token
SAKILA_ADMIN_TOKEN=`jq -r .auth.client_token sakila-admin.token`
VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault read auth/token/lookup-self

read
clear
echo "And use the sakila-admin token to fetch some database credentials"
echo
echo
echo "vault read database/creds/sakila-admin"
VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault read database/creds/sakila-admin -format=json > sakila-admin.creds
jq . sakila-admin.creds


read
clear
echo "Let's try those credentials out"
SAKILA_DB_USER=`jq -r .data.username sakila-admin.creds`
SAKILA_DB_PASS=`jq -r .data.password sakila-admin.creds`
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read
echo "Now let's revoke those credentials and see what happens"
echo "vault token revoke -self"
VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault token revoke -self
read
echo
echo
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read

clear
echo "Let's do the same for the sakila-backend policy"
echo "This time, however, let's make direct use of the Vault RESTful API"
echo
echo
cat <<EOF | tee sakila-backend.request.json
{
  "policies": ["sakila-backend"]
}
EOF
read

clear
echo
echo
echo 'curl -s \
  --header "X-Vault-Token: ${VAULT_ROOT_TOKEN}" \
  --request POST \
  --data @sakila-backend.request.json \
  ${VAULT_ADDR}/v1/auth/token/create > sakila-backend.token'
curl -s \
  --header "X-Vault-Token: ${VAULT_ROOT_TOKEN}" \
  --request POST \
  --data @sakila-backend.request.json \
  ${VAULT_ADDR}/v1/auth/token/create > sakila-backend.token
read

clear
jq . sakila-backend.token
SAKILA_BACKEND_TOKEN=`jq -r .auth.client_token sakila-backend.token`

read
clear
echo "And use the sakila-backend token to fetch some database credentials"
echo
echo
echo 'curl -s \
  --header "X-Vault-Token: $SAKILA_BACKEND_TOKEN" \
  ${VAULT_ADDR}/v1/database/creds/sakila-backend > sakila-backend.creds'
curl -s \
  --header "X-Vault-Token: $SAKILA_BACKEND_TOKEN" \
  ${VAULT_ADDR}/v1/database/creds/sakila-backend > sakila-backend.creds

read
clear
jq . sakila-backend.creds


read
clear
echo "Let's try those credentials out"
SAKILA_DB_USER=`jq -r .data.username sakila-backend.creds`
SAKILA_DB_PASS=`jq -r .data.password sakila-backend.creds`
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read
echo "Now let's revoke those credentials and see what happens"
echo "vault token revoke -self"
VAULT_TOKEN=$SAKILA_BACKEND_TOKEN vault token revoke -self
read
echo
echo
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
